services:
  server:
    image: myfinal12/dian-server:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/app/config
      - ./plugins:/app/plugins
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - dian

  web:
    image: myfinal12/dian-web:latest
    ports:
      - "18099:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - dian

networks:
  dian:
    driver: bridge
